#!/usr/bin/env python3
"""Generate BetterTG/Secret/Secret.swift from api_id and api_hash (Windows/macOS/Linux)."""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path


def chunks(seq: list[int], size: int):
    for i in range(0, len(seq), size):
        yield seq[i : i + size]


def encode(value: str, cipher: list[int]) -> list[int]:
    data = value.encode("utf-8")
    return [data[i] ^ cipher[i % len(cipher)] for i in range(len(data))]


def format_byte_lines(values: list[int], indent: str = "        ") -> str:
    lines: list[str] = []
    for chunk in chunks(values, 8):
        line = "".join(f"0x{b:02x}, " for b in chunk)
        lines.append(f"{indent}{line}")
    return "\n".join(lines)


def generate(api_id: str, api_hash: str) -> str:
    salt = [secrets.randbelow(256) for _ in range(64)]
    encoded_id = encode(api_id, salt)
    encoded_hash = encode(api_hash, salt)

    return f"""// Secret.swift — generated by generate_secret.py

public struct Secret {{
    private static let salt: [UInt8] = [
{format_byte_lines(salt)}
    ]

    public static var apiId: Int {{
        let encoded: [UInt8] = [
{format_byte_lines(encoded_id)}
        ]

        return Int(decode(encoded, cipher: salt))!
    }}

    public static var apiHash: String {{
        let encoded: [UInt8] = [
{format_byte_lines(encoded_hash)}
        ]

        return decode(encoded, cipher: salt)
    }}

    public static func decode(_ encoded: [UInt8], cipher: [UInt8]) -> String {{
        String(decoding: encoded.enumerated().map {{ (offset, element) in
            element ^ cipher[offset % cipher.count]
        }}, as: UTF8.self)
    }}

    private init() {{ }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate BetterTG/Secret/Secret.swift for local builds."
    )
    parser.add_argument("api_id", help="Telegram api_id from https://my.telegram.org/")
    parser.add_argument("api_hash", help="Telegram api_hash from https://my.telegram.org/")
    args = parser.parse_args()

    if not str(args.api_id).isdigit():
        print("api_id must be a number.", file=sys.stderr)
        return 1

    if len(args.api_hash.strip()) < 16:
        print("api_hash looks too short.", file=sys.stderr)
        return 1

    out = Path(__file__).resolve().parent / "BetterTG" / "Secret" / "Secret.swift"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(str(args.api_id), args.api_hash.strip()), encoding="utf-8")
    print(f"Wrote {out}")
    print("Next: open BetterTG.xcodeproj on a Mac with Xcode and build for your iPhone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
